import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Copy, Check, RefreshCw } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { getAuthenticatedBackend } from "../lib/backend";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

interface ProfileReferenceCodeDisplayProps {
  entityType: "accommodation" | "restaurant" | "service" | "attraction";
  entityId: number;
  entityStringId?: string;
  currentCode?: string | null;
  onCodeUpdated?: (newCode: string) => void;
}

export default function ProfileReferenceCodeDisplay({
  entityType,
  entityId,
  currentCode,
}: ProfileReferenceCodeDisplayProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const displayCode = currentCode || "";

  // The partner "edit code" applies to the three partner entity types, not to
  // accommodations. It is fetched separately (it is never part of the entity
  // JSON, to avoid leaking it to guests).
  const supportsEditCode =
    entityType === "restaurant" || entityType === "service" || entityType === "attraction";
  const [editCode, setEditCode] = useState<string | null>(null);
  const [editCopied, setEditCopied] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [showRegenDialog, setShowRegenDialog] = useState(false);

  useEffect(() => {
    if (!supportsEditCode || !entityId) return;
    (async () => {
      try {
        const backend = getAuthenticatedBackend();
        const res = await backend.editCode.get({ entityType, entityId });
        setEditCode((res as { editCode?: string }).editCode ?? null);
      } catch (error) {
        console.error("Failed to load edit code:", error);
      }
    })();
  }, [entityType, entityId, supportsEditCode]);

  const copyToClipboard = () => {
    if (displayCode) {
      navigator.clipboard.writeText(displayCode);
      setCopied(true);
      toast({ title: "Copied!", description: "Profile access code copied to clipboard" });
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const copyEditCode = () => {
    if (editCode) {
      navigator.clipboard.writeText(editCode);
      setEditCopied(true);
      toast({ title: "Copied!", description: "Partner edit code copied to clipboard" });
      setTimeout(() => setEditCopied(false), 2000);
    }
  };

  const handleRegenerateEdit = async () => {
    setIsRegenerating(true);
    try {
      const backend = getAuthenticatedBackend();
      const res = await backend.editCode.regenerate({ entityType, entityId });
      setEditCode((res as { editCode?: string }).editCode ?? null);
      toast({ title: "Edit Code Regenerated", description: "Share the new edit code with the partner." });
    } catch (error) {
      console.error("Failed to regenerate edit code:", error);
      toast({ title: "Error", description: "Failed to regenerate edit code. Please try again.", variant: "destructive" });
    } finally {
      setIsRegenerating(false);
      setShowRegenDialog(false);
    }
  };

  return (
    <>
      <div className="space-y-2 p-4 bg-muted/50 rounded-lg border border-border">
        <Label className="text-base font-semibold text-foreground">Profile Access Code</Label>
        <p className="text-xs text-muted-foreground">
          This code is automatically generated by the system and is the unique login credential for this profile. Keep it confidential.
        </p>
        <div className="flex gap-2 items-center">
          <Input value={displayCode} readOnly className="font-mono tracking-widest" />
          <Button type="button" variant="outline" size="sm" onClick={copyToClipboard} disabled={!displayCode}>
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
          </Button>
        </div>

        {supportsEditCode && (
          <div className="pt-3 mt-2 border-t border-border space-y-2">
            <Label className="text-base font-semibold text-foreground">Partner Edit Code</Label>
            <p className="text-xs text-muted-foreground">
              Give this to the partner so they can edit their own profile from the Partner Dashboard. It is separate from the login code above and does not grant login.
            </p>
            <div className="flex gap-2 items-center">
              <Input value={editCode ?? ""} readOnly className="font-mono tracking-widest" placeholder="—" />
              <Button type="button" variant="outline" size="sm" onClick={copyEditCode} disabled={!editCode}>
                {editCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              </Button>
              <Button type="button" variant="outline" size="sm" onClick={() => setShowRegenDialog(true)} disabled={isRegenerating} title="Regenerate edit code">
                <RefreshCw className="h-4 w-4" />
              </Button>
            </div>
          </div>
        )}
      </div>

      <AlertDialog open={showRegenDialog} onOpenChange={setShowRegenDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Regenerate Edit Code?</AlertDialogTitle>
            <AlertDialogDescription>
              This generates a new edit code and invalidates the current one. A partner using the old edit code will need the new one to edit their profile. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleRegenerateEdit} disabled={isRegenerating}>
              {isRegenerating ? "Regenerating..." : "Regenerate"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
