-- ============================================================================
-- 000002_create_users_sessions
-- ============================================================================
-- Replaces appdb.DB.Users / appdb.DB.Sessions (plain in-memory Go maps) with
-- real tables. The in-memory version meant every server restart silently
-- invalidated every session — not a JWT-signing issue (this backend never
-- used JWTs; tokens are opaque random strings looked up here), just a plain
-- "the map got wiped" issue. Persisting both fixes that directly.
--
-- Idempotent (if not exists / on conflict) so it's safe against both a fresh
-- database and one that already has these tables from a previous partial run.
-- ============================================================================

create table if not exists users (
  id                bigint generated by default as identity primary key,

  email             text not null,
  role              text not null, -- 'Guest' | 'LocalGuest' | 'Partner' | 'SuperAdmin'
  profile_type      text,          -- 'accommodation' | 'restaurant' | 'service' | 'attraction'
  accommodation_id  bigint,
  entity_type       text,          -- 'restaurant' | 'service' | 'attraction'
  entity_id         bigint,
  area              text,
  municipality      text,

  created_at        timestamptz not null default now()
);

-- Matches the existing findLocalGuestByEmail lookup pattern (role +
-- case-insensitive email); not unique since a fresh Guest/Partner login can
-- legitimately create a new synthetic user row without colliding.
create index if not exists idx_users_role_email on users (role, lower(email));

create table if not exists sessions (
  token       text primary key,
  user_id     bigint not null references users (id) on delete cascade,
  created_at  timestamptz not null default now()
);

create index if not exists idx_sessions_user_id on sessions (user_id);
