-- ============================================================================
-- 000001_create_accommodations
-- ============================================================================
-- Pure-Postgres schema for the accommodations table, applied by the built-in
-- migration runner (internal/appdb/migrate.go). No Row Level Security or role
-- creation — auth is enforced in the Go layer, not the database.
--
-- Written to be idempotent so it is safe to run against BOTH a fresh database
-- and an existing Supabase project that already has this table (created by
-- supabase/migrations/20260721095109_init_schema.sql). Everything uses
-- "if not exists" / "on conflict" / drop-before-create, and the demo seed row
-- is only inserted when the table is empty so it never lands in real data.
--
-- Scoped to accommodations only — restaurants/services/attractions/users/
-- sessions/profile_settings are still the in-memory appdb.DB store and will
-- get their own numbered migration (000002_..., etc.) as each one moves to SQL.
-- ============================================================================

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists accommodations (
  id                        bigint generated by default as identity primary key,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text,
  postal_code               text not null default '',

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,
  facilities                text[] not null default '{}',

  wifi_name                 text,
  wifi_password             text,
  wifi_credentials          text,

  check_in_instructions     text,
  check_out_instructions    text,
  amenities                 text,
  guidelines                text,

  primary_contact           text,
  police_contact            text,
  doctor_contact            text,
  ambulance_contact         text,
  hospital_contact          text,
  fire_department_contact   text,

  -- appdb.EmergencyContact[] — kept as jsonb rather than a child table since
  -- it's always read/written as a single unit (AccommodationForm.tsx), never
  -- queried/filtered on individually.
  emergency_contacts        jsonb not null default '[]',

  image_url                 text,
  image_urls                text[] not null default '{}',

  is_active                 boolean not null default true,

  official_holding_company  text,
  official_contact_name     text,
  official_contact_number   text,
  official_email            text,
  official_rep_code         text,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists idx_accommodations_province on accommodations (province);
create index if not exists idx_accommodations_area on accommodations (area);
create index if not exists idx_accommodations_is_active on accommodations (is_active);
create index if not exists idx_accommodations_lat_lng on accommodations (latitude, longitude);

drop trigger if exists trg_accommodations_updated_at on accommodations;
create trigger trg_accommodations_updated_at
  before update on accommodations
  for each row execute function set_updated_at();

-- Minimal seed row for smoke testing, inserted ONLY when the table is empty,
-- so running against an existing/populated database is a no-op.
insert into accommodations
  (name, address, latitude, longitude, country, province, area, postal_code,
   profile_reference_code, wheelchair_access, parking_availability, facilities,
   wifi_name, wifi_password, is_active)
select
  'Seaview Guesthouse', '12 Beach Rd', -33.0117, 18.0387, 'South Africa',
  'Western Cape', 'Saldanha', '7395', 'SEAVW01', true, true,
  array['Pool', 'Braai area', 'Sea view'], 'SeaviewGuest', 'welcome2026', true
where not exists (select 1 from accommodations);
