-- ============================================================================
-- 000010_create_restaurants_services_attractions
-- ============================================================================
-- Restaurants, Services, and Attractions have been stored ONLY in an
-- in-memory Go map since this project began — the same category of issue
-- Accommodation already had fixed. In-memory means every server restart
-- (which Fly does automatically to save cost when idle) silently wipes
-- everything: every restaurant a rep onboards, gone, with no warning.
--
-- This migration creates real tables for all three, matching
-- appdb.Restaurant / appdb.ServiceData / appdb.AttractionData exactly.
-- Nullable text columns get a '' default from the start (see
-- 000003_null_safety_defaults.sql for why this matters — the accommodations
-- table needed a whole separate follow-up migration to add these after the
-- fact; doing it here up front avoids repeating that).
-- ============================================================================

create table if not exists restaurants (
  id                        bigint generated by default as identity primary key,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text default '',
  postal_code               text not null default '',
  contact_number            text default '',
  description               text default '',

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text default '',

  cuisine_types             text[] not null default '{}',
  menu_link                 text default '',
  service_dine_in           boolean not null default false,
  service_takeaway          boolean not null default false,
  service_delivery          boolean not null default false,
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  wifi_network              text default '',
  wifi_password             text default '',
  wifi_credentials          text default '',

  discount_offered          text default '',
  discount_code             text default '',

  image_url                 text default '',
  is_active                 boolean not null default true,

  official_holding_company  text default '',
  official_contact_name     text default '',
  official_contact_number   text default '',
  official_email            text default '',
  official_rep_code         text default '',
  guest_type                text default '',
  access_level              text default '',

  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists idx_restaurants_province on restaurants (province);
create index if not exists idx_restaurants_area on restaurants (area);
create index if not exists idx_restaurants_is_active on restaurants (is_active);
create index if not exists idx_restaurants_lat_lng on restaurants (latitude, longitude);

create trigger trg_restaurants_updated_at
  before update on restaurants
  for each row execute function set_updated_at();

-- ============================================================================
create table if not exists services (
  id                        bigint generated by default as identity primary key,
  service_id                text generated always as (id::text) stored,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text default '',
  postal_code               text not null default '',
  contact_number            text default '',
  description               text default '',

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text default '',

  service_categories        text[] not null default '{}',
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  discount_offered          text default '',
  discount_code             text default '',

  image_url                 text default '',
  is_active                 boolean not null default true,

  official_holding_company  text default '',
  official_contact_name     text default '',
  official_contact_number   text default '',
  official_email            text default '',
  official_rep_code         text default '',
  guest_type                text default '',
  access_level              text default '',

  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create unique index if not exists idx_services_service_id on services (service_id);
create index if not exists idx_services_province on services (province);
create index if not exists idx_services_area on services (area);
create index if not exists idx_services_is_active on services (is_active);
create index if not exists idx_services_lat_lng on services (latitude, longitude);

create trigger trg_services_updated_at
  before update on services
  for each row execute function set_updated_at();

-- ============================================================================
create table if not exists attractions (
  id                        bigint generated by default as identity primary key,
  attraction_id             text generated always as (id::text) stored,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text default '',
  postal_code               text not null default '',
  contact_number            text default '',
  description               text default '',

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text default '',

  attraction_type           text[] not null default '{}',
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  discount_offered          text default '',
  discount_code             text default '',

  image_url                 text default '',
  is_active                 boolean not null default true,

  official_holding_company  text default '',
  official_contact_name     text default '',
  official_contact_number   text default '',
  official_email            text default '',
  official_rep_code         text default '',
  guest_type                text default '',
  access_level              text default '',

  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create unique index if not exists idx_attractions_attraction_id on attractions (attraction_id);
create index if not exists idx_attractions_province on attractions (province);
create index if not exists idx_attractions_area on attractions (area);
create index if not exists idx_attractions_is_active on attractions (is_active);
create index if not exists idx_attractions_lat_lng on attractions (latitude, longitude);

create trigger trg_attractions_updated_at
  before update on attractions
  for each row execute function set_updated_at();
