-- Purge all accounting + analytics generated by the internal/test rep
-- Rep00000001, WITHOUT touching the "Test …" partner profiles themselves.
-- After this runs there are no outstanding invoices, no commissions, and no
-- analytics rows attributable to that rep, so the dashboards and books read as
-- if those test partners never billed.
--
-- The set of test-rep partners is (partner_type, partner_id) whose listing has
-- official_rep_code = Rep00000001 (case-insensitive). Deleted in FK-safe order:
-- commissions → invoices (line items + remaining commissions cascade) →
-- subscriptions → events / charity / bookings.

-- 1) Commissions earned by, or overridden from, the test rep.
delete from commission
 where lower(rep_code) = 'rep00000001'
    or lower(coalesce(source_rep_code, '')) = 'rep00000001';

-- 2) Invoices for the test rep (by snapshot rep code OR by owning partner).
--    invoice_line_item and any remaining commission rows cascade on delete.
delete from invoice
 where lower(coalesce(bill_rep_code, '')) = 'rep00000001'
    or (partner_type, partner_id) in (
        select 'restaurant', id     from restaurants   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'service', id       from services      where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'attraction', id    from attractions   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'accommodation', id from accommodations where lower(coalesce(official_rep_code, '')) = 'rep00000001'
    );

-- 3) Subscriptions (recurring monthly charge) for the test rep / its partners.
delete from partner_subscription
 where lower(coalesce(rep_code, '')) = 'rep00000001'
    or (partner_type, partner_id) in (
        select 'restaurant', id     from restaurants   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'service', id       from services      where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'attraction', id    from attractions   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'accommodation', id from accommodations where lower(coalesce(official_rep_code, '')) = 'rep00000001'
    );

-- 4) Behavioural events (QR scans, listing views, …) for those partners.
delete from events
 where (entity_type, entity_id) in (
        select 'restaurant', id     from restaurants   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'service', id       from services      where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'attraction', id    from attractions   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'accommodation', id from accommodations where lower(coalesce(official_rep_code, '')) = 'rep00000001'
    );

-- 5) Charity selections (analytics) for those partners.
delete from partner_charity
 where (partner_type, partner_id) in (
        select 'restaurant', id     from restaurants   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'service', id       from services      where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'attraction', id    from attractions   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'accommodation', id from accommodations where lower(coalesce(official_rep_code, '')) = 'rep00000001'
    );

-- 6) Bookings (GMV / per-cover commission source) for those partners.
delete from bookings
 where (entity_type, entity_id) in (
        select 'restaurant', id     from restaurants   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'service', id       from services      where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'attraction', id    from attractions   where lower(coalesce(official_rep_code, '')) = 'rep00000001'
        union all select 'accommodation', id from accommodations where lower(coalesce(official_rep_code, '')) = 'rep00000001'
    );
