-- ============================================================================
-- users / sessions (Supabase/production variant)
-- ============================================================================
-- Same tables as migrations/000002_create_users_sessions.sql (the pure-Go
-- variant). See that file's header for why they exist.
-- ============================================================================

create table if not exists users (
  id                bigint generated by default as identity primary key,

  email             text not null,
  role              text not null,
  profile_type      text,
  accommodation_id  bigint,
  entity_type       text,
  entity_id         bigint,
  area              text,
  municipality      text,

  created_at        timestamptz not null default now()
);

create index if not exists idx_users_role_email on users (role, lower(email));

create table if not exists sessions (
  token       text primary key,
  user_id     bigint not null references users (id) on delete cascade,
  created_at  timestamptz not null default now()
);

create index if not exists idx_sessions_user_id on sessions (user_id);

alter table users    enable row level security;
alter table sessions enable row level security;

-- No anon/authenticated policies at all — this app's auth is custom
-- (bearer-token sessions, not Supabase Auth), so these tables should only
-- ever be touched by the Go backend's own database role, which must bypass
-- RLS (BYPASSRLS or the service_role key). Locked down by default for
-- anon/authenticated, matching the same reasoning as the main schema file.
