-- ============================================================================
-- Around You — initial schema
-- ============================================================================
-- Mirrors app/appdb/schema.go exactly (Accommodation, Restaurant, ServiceData,
-- AttractionData, User, ProfileSettings, sessions), which was itself built by
-- reading every frontend Form/List/Tab component's actual field usage — see
-- the Phase 1 architecture report. Applying this + rewiring app/appdb's Store
-- to issue real queries (via encore.dev/storage/sqldb) replaces the in-memory
-- map store with this database.
--
-- HOW TO APPLY
--   Supabase CLI:  supabase db push
--   Or paste this whole file into the Supabase Dashboard's SQL Editor and run it.
--
-- CONNECTION MODEL / RLS NOTE (read before enabling this in production)
--   This app has its own auth (email/access-code -> session token in the
--   `sessions` table below), not Supabase Auth. The Encore backend should
--   connect with a role that bypasses RLS entirely — Supabase's `service_role`
--   key if you're going through Supabase's pooler/PostgREST, or a plain
--   Postgres role with BYPASSRLS if Encore connects directly (the more likely
--   setup, since Encore talks straight to Postgres, not through PostgREST).
--   The RLS policies below are a *defense-in-depth* baseline for the
--   `anon`/`authenticated` roles only, in case the frontend or something else
--   ever queries Supabase directly with the anon key. They intentionally
--   expose nothing except read-only access to already-public, active listings.
-- ============================================================================


-- ============================================================================
-- Extensions
-- ============================================================================
create extension if not exists pgcrypto; -- gen_random_uuid(), not required yet but cheap to have on hand


-- ============================================================================
-- Shared trigger: keep updated_at current on every UPDATE
-- ============================================================================
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================================
-- accommodations
-- Matches appdb.Accommodation. Guests log in against these (role "Guest").
-- ============================================================================
create table accommodations (
  id                        bigint generated by default as identity primary key,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text,
  postal_code               text not null default '',

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,
  facilities                text[] not null default '{}',

  wifi_name                 text,
  wifi_password             text,
  wifi_credentials          text,

  check_in_instructions     text,
  check_out_instructions    text,
  amenities                 text,
  guidelines                text,

  primary_contact           text,
  police_contact            text,
  doctor_contact            text,
  ambulance_contact         text,
  hospital_contact          text,
  fire_department_contact   text,

  -- appdb.EmergencyContact[] — kept as jsonb rather than a child table since
  -- it's always read/written as a single unit (see AccommodationForm.tsx),
  -- never queried/filtered on individually.
  emergency_contacts        jsonb not null default '[]',

  image_url                 text,
  image_urls                text[] not null default '{}',

  is_active                 boolean not null default true,

  -- appdb.OfficialUse (accommodations don't use guest_type/access_level —
  -- confirmed by AccommodationForm.tsx only sending the 5 fields below)
  official_holding_company  text,
  official_contact_name     text,
  official_contact_number   text,
  official_email            text,
  official_rep_code         text,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index idx_accommodations_province on accommodations (province);
create index idx_accommodations_area on accommodations (area);
create index idx_accommodations_is_active on accommodations (is_active);
-- Plain btree — fine for exact/range filters. If "nearby" search is ever
-- needed for accommodations too, switch to PostGIS geography + a GiST index
-- (see the note above ListNearby on restaurants/services/attractions below).
create index idx_accommodations_lat_lng on accommodations (latitude, longitude);

create trigger trg_accommodations_updated_at
  before update on accommodations
  for each row execute function set_updated_at();


-- ============================================================================
-- restaurants
-- Matches appdb.Restaurant (embeds OfficialUse + PartnerCode).
-- ============================================================================
create table restaurants (
  id                        bigint generated by default as identity primary key,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text,
  postal_code               text not null default '',
  contact_number            text,
  description               text,

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text,

  cuisine_types             text[] not null default '{}',
  menu_link                 text,
  service_dine_in           boolean not null default false,
  service_takeaway          boolean not null default false,
  service_delivery          boolean not null default false,
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  wifi_network              text,
  wifi_password             text,
  wifi_credentials          text,

  discount_offered          text,
  discount_code             text,

  image_url                 text,
  is_active                 boolean not null default true,

  -- appdb.OfficialUse (restaurants DO use guest_type/access_level — see
  -- ProfileClassificationGroups.tsx reading restaurant.guestType/accessLevel)
  official_holding_company  text,
  official_contact_name     text,
  official_contact_number   text,
  official_email            text,
  official_rep_code         text,
  guest_type                text,
  access_level              text,

  -- appdb.PartnerCode
  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index idx_restaurants_province on restaurants (province);
create index idx_restaurants_area on restaurants (area);
create index idx_restaurants_is_active on restaurants (is_active);
-- Supports ListNearby's radius scan. HaversineKm in Go does the actual
-- distance math, so this index only narrows the candidate set — for a much
-- faster true nearest-neighbor query at scale, enable the PostGIS extension,
-- add a `geography(Point,4326)` generated column from (longitude, latitude),
-- and index that with GiST instead.
create index idx_restaurants_lat_lng on restaurants (latitude, longitude);

create trigger trg_restaurants_updated_at
  before update on restaurants
  for each row execute function set_updated_at();


-- ============================================================================
-- services
-- Matches appdb.ServiceData. service_id is a generated column — it's always
-- just the string form of id (see the dual-identifier note in schema.go), so
-- deriving it in SQL keeps the two permanently in sync with zero app code.
-- ============================================================================
create table services (
  id                        bigint generated by default as identity primary key,
  service_id                text generated always as (id::text) stored,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text,
  postal_code               text not null default '',
  contact_number            text,
  description               text,

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text,

  service_categories        text[] not null default '{}',
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  discount_offered          text,
  discount_code             text,

  image_url                 text,
  is_active                 boolean not null default true,

  official_holding_company  text,
  official_contact_name     text,
  official_contact_number   text,
  official_email            text,
  official_rep_code         text,
  guest_type                text,
  access_level              text,

  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create unique index idx_services_service_id on services (service_id);
create index idx_services_province on services (province);
create index idx_services_area on services (area);
create index idx_services_is_active on services (is_active);
create index idx_services_lat_lng on services (latitude, longitude);

create trigger trg_services_updated_at
  before update on services
  for each row execute function set_updated_at();


-- ============================================================================
-- attractions
-- Matches appdb.AttractionData. Same generated-column pattern as services.
-- ============================================================================
create table attractions (
  id                        bigint generated by default as identity primary key,
  attraction_id             text generated always as (id::text) stored,

  name                      text not null,
  address                   text not null,

  latitude                  double precision,
  longitude                 double precision,

  country                   text not null default '',
  province                  text not null,
  area                      text,
  postal_code               text not null default '',
  contact_number            text,
  description               text,

  profile_reference_code    text unique,
  is_duplicate              boolean not null default false,
  duplicate_reason          text,

  attraction_type           text[] not null default '{}',
  little_explorer_approved  boolean not null default false,

  payment_card              boolean not null default false,
  payment_cash              boolean not null default false,
  payment_mobile            boolean not null default false,

  wheelchair_access         boolean not null default false,
  parking_availability      boolean not null default false,

  discount_offered          text,
  discount_code             text,

  image_url                 text,
  is_active                 boolean not null default true,

  official_holding_company  text,
  official_contact_name     text,
  official_contact_number   text,
  official_email            text,
  official_rep_code         text,
  guest_type                text,
  access_level              text,

  partner_code              text unique,
  partner_code_active       boolean not null default true,

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create unique index idx_attractions_attraction_id on attractions (attraction_id);
create index idx_attractions_province on attractions (province);
create index idx_attractions_area on attractions (area);
create index idx_attractions_is_active on attractions (is_active);
create index idx_attractions_lat_lng on attractions (latitude, longitude);

create trigger trg_attractions_updated_at
  before update on attractions
  for each row execute function set_updated_at();


-- ============================================================================
-- users
-- Matches appdb.User. NOTE: auth.go's AccessCodeLogin/SecondaryLogin currently
-- create a brand-new user row on every login rather than reusing one (only
-- LocalGuestLogin dedupes, by role+email) — this schema intentionally does
-- NOT add a unique constraint on email, or rows would start failing to insert
-- the moment two guests share a synthetic "guest@<business name>" email.
-- Tighten this once/if the login handlers are changed to dedupe guests too.
-- ============================================================================
create table users (
  id                 bigint generated by default as identity primary key,

  email              text not null,
  role               text not null
                       check (role in ('Guest', 'LocalGuest', 'Partner', 'SuperAdmin')),
  profile_type       text
                       check (profile_type is null or profile_type in ('accommodation', 'restaurant', 'service', 'attraction')),

  accommodation_id   bigint references accommodations (id) on delete set null,

  -- entity_type/entity_id together are a polymorphic reference into
  -- restaurants/services/attractions depending on entity_type. Postgres has
  -- no native polymorphic FK — enforce with a trigger below rather than a
  -- plain FK constraint (or normalize into per-type nullable FK columns if
  -- you'd rather trade the trigger for three always-nullable FKs).
  entity_type        text
                       check (entity_type is null or entity_type in ('restaurant', 'service', 'attraction')),
  entity_id          bigint,

  area               text,
  municipality       text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index idx_users_accommodation_id on users (accommodation_id);
create index idx_users_entity on users (entity_type, entity_id);
create index idx_users_role_email on users (role, email);

create trigger trg_users_updated_at
  before update on users
  for each row execute function set_updated_at();

-- Polymorphic FK enforcement: whenever entity_type/entity_id is set, make
-- sure it actually points at an existing row in the right table.
create or replace function check_user_entity_reference()
returns trigger
language plpgsql
as $$
begin
  if new.entity_type is null then
    return new;
  end if;

  if new.entity_type = 'restaurant' and not exists (select 1 from restaurants where id = new.entity_id) then
    raise exception 'users.entity_id % does not reference an existing restaurant', new.entity_id;
  elsif new.entity_type = 'service' and not exists (select 1 from services where id = new.entity_id) then
    raise exception 'users.entity_id % does not reference an existing service', new.entity_id;
  elsif new.entity_type = 'attraction' and not exists (select 1 from attractions where id = new.entity_id) then
    raise exception 'users.entity_id % does not reference an existing attraction', new.entity_id;
  end if;

  return new;
end;
$$;

create trigger trg_users_check_entity_reference
  before insert or update on users
  for each row execute function check_user_entity_reference();


-- ============================================================================
-- sessions
-- Matches appdb.Store.Sessions (token -> user ID). Bearer tokens minted by
-- auth.go's issueSession.
-- ============================================================================
create table sessions (
  token       text primary key,
  user_id     bigint not null references users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  -- Not read by the current Go handlers (auth.go never checks expiry), but
  -- worth having in the schema so expiry can be added without a migration —
  -- e.g. `delete from sessions where expires_at < now()` on a cron.
  expires_at  timestamptz
);

create index idx_sessions_user_id on sessions (user_id);


-- ============================================================================
-- profile_settings
-- Matches appdb.Store.ProfileSettings + LogoURL — confirmed single,
-- platform-wide record (see BookingsSocialsDropdowns.tsx and
-- RestaurantTab.tsx, neither of which passes an entity ID). Singleton table:
-- exactly one row, enforced by the id=1 check constraint.
-- ============================================================================
create table profile_settings (
  id                        smallint primary key default 1 check (id = 1),

  bookings_email            text,
  bookings_contact_number   text,
  socials_website           text,
  socials_instagram         text,
  socials_twitter           text,
  socials_youtube           text,
  socials_tiktok            text,

  logo_url                  text,

  updated_at                timestamptz not null default now()
);

create trigger trg_profile_settings_updated_at
  before update on profile_settings
  for each row execute function set_updated_at();


-- ============================================================================
-- Row Level Security
-- See the connection-model note at the top of this file before relying on
-- these. Locked down by default; only read access to already-public, active
-- listings is opened up for anon/authenticated.
-- ============================================================================
alter table accommodations   enable row level security;
alter table restaurants      enable row level security;
alter table services         enable row level security;
alter table attractions      enable row level security;
alter table users            enable row level security;
alter table sessions         enable row level security;
alter table profile_settings enable row level security;

-- Public, read-only access to active listings only (mirrors what guests can
-- already see through the app itself via GuestDashboard.tsx's
-- listByMunicipality/listNearby). Everything else — inserts, updates,
-- deletes, and all of users/sessions/profile_settings — has no anon/
-- authenticated policy at all, so it's denied by default under RLS.
create policy "Public can read active accommodations"
  on accommodations for select
  to anon, authenticated
  using (is_active = true);

create policy "Public can read active restaurants"
  on restaurants for select
  to anon, authenticated
  using (is_active = true);

create policy "Public can read active services"
  on services for select
  to anon, authenticated
  using (is_active = true);

create policy "Public can read active attractions"
  on attractions for select
  to anon, authenticated
  using (is_active = true);

-- profile_settings (logo, booking/social links) is app-wide marketing info,
-- safe to expose publicly for read — matches LogoPlaceholder.tsx and
-- BookingsSocialsDropdowns.tsx both being reachable from public/guest screens.
create policy "Public can read platform profile settings"
  on profile_settings for select
  to anon, authenticated
  using (true);


-- ============================================================================
-- Seed data — enough to smoke-test every handler in accommodation/,
-- restaurant/, service/, attraction/, auth/, stats/, and storage/ without
-- needing the app running first.
-- ============================================================================

insert into accommodations
  (id, name, address, latitude, longitude, country, province, area, postal_code,
   profile_reference_code, wheelchair_access, parking_availability, facilities,
   wifi_name, wifi_password, is_active)
values
  (1, 'Seaview Guesthouse', '12 Beach Rd', -33.0117, 18.0387, 'South Africa',
   'Western Cape', 'Saldanha', '7395', 'SEAVW01', true, true,
   array['Pool', 'Braai area', 'Sea view'], 'SeaviewGuest', 'welcome2026', true);

insert into restaurants
  (id, name, address, latitude, longitude, country, province, area, postal_code,
   contact_number, description, profile_reference_code, cuisine_types,
   service_dine_in, service_takeaway, payment_card, payment_cash,
   wheelchair_access, parking_availability, image_url, is_active,
   partner_code, partner_code_active)
values
  (1, 'Harbour Bistro', '4 Harbour St', -33.0125, 18.0011, 'South Africa',
   'Western Cape', 'Saldanha', '7395', '+27 22 000 0001',
   'Fresh seafood overlooking the bay.', 'HARBOR01',
   array['Seafood', 'South African'], true, true, true, true, true, true,
   'https://example.com/harbour-bistro.jpg', true, 'HBPARTNER1', true),
  (2, 'Blue Anchor Café', '9 Main Rd', -33.0143, 17.9432, 'South Africa',
   'Western Cape', 'Vredenburg', '7380', '+27 22 000 0002',
   'Casual all-day breakfast spot.', 'BLUEANCH1',
   array['Café', 'Breakfast'], true, false, true, true, false, true,
   'https://example.com/blue-anchor.jpg', true, 'BAPARTNER2', true);

insert into services
  (id, name, address, latitude, longitude, country, province, area, postal_code,
   contact_number, description, profile_reference_code, service_categories,
   payment_card, payment_cash, wheelchair_access, parking_availability,
   image_url, is_active, partner_code, partner_code_active)
values
  (1, 'West Coast Dive Charters', '1 Jetty Rd', -33.0098, 17.9531, 'South Africa',
   'Western Cape', 'Saldanha', '7395', '+27 22 000 0101',
   'Guided scuba diving and boat charters.', 'DIVECHAR1',
   array['Watersports', 'Tours'], true, true, false, true,
   'https://example.com/dive-charters.jpg', true, 'DCPARTNER1', true);

insert into attractions
  (id, name, address, latitude, longitude, country, province, area, postal_code,
   contact_number, description, profile_reference_code, attraction_type,
   payment_card, payment_cash, wheelchair_access, parking_availability,
   image_url, is_active, partner_code, partner_code_active)
values
  (1, 'Saldanha Bay Lighthouse', 'Lighthouse Rd', -33.0361, 17.9540, 'South Africa',
   'Western Cape', 'Saldanha', '7395', '+27 22 000 0201',
   'Historic working lighthouse with public tours.', 'LIGHTHSE1',
   array['Landmark', 'Sightseeing'], false, true, false, true,
   'https://example.com/lighthouse.jpg', true, 'LHPARTNER1', true);

-- A SuperAdmin so AdminLoginPage.tsx / AdminDashboard.tsx have something to
-- sign in as during smoke testing. auth.go doesn't currently have a
-- SuperAdmin-issuing login path (see Phase 1 report — every login endpoint
-- infers role from what it matches), so for now this row exists to unblock
-- manual testing via a session token inserted directly, e.g.:
--   insert into sessions (token, user_id) values ('dev-admin-token', 1);
insert into users (id, email, role)
values (1, 'admin@aroundyou.example', 'SuperAdmin');

insert into profile_settings (id, bookings_email, bookings_contact_number, socials_website, logo_url)
values (1, 'bookings@aroundyou.example', '+27 22 000 0000', 'https://aroundyou.example', null);

-- Keep the identity sequences ahead of the explicit IDs inserted above so the
-- next app-issued Create() doesn't collide with seed data.
select setval(pg_get_serial_sequence('accommodations', 'id'), (select max(id) from accommodations));
select setval(pg_get_serial_sequence('restaurants', 'id'), (select max(id) from restaurants));
select setval(pg_get_serial_sequence('services', 'id'), (select max(id) from services));
select setval(pg_get_serial_sequence('attractions', 'id'), (select max(id) from attractions));
select setval(pg_get_serial_sequence('users', 'id'), (select max(id) from users));
