-- ============================================================================
-- 000003_null_safety_defaults
-- ============================================================================
-- The COALESCE fixes in store/sql_store.go and app/auth/auth.go stop NULLs
-- from crashing a scan today, but they only help if every future SELECT
-- remembers to include them. This migration removes the underlying
-- possibility instead: backfill every existing NULL to '' (or 0 for the
-- nullable bigints), then set a DEFAULT so newly inserted rows can't
-- reintroduce a NULL in these columns even via a manual INSERT that bypasses
-- the Go layer entirely (e.g. a one-off `psql` fix, a future migration, an
-- admin script).
--
-- Deliberately NOT adding NOT NULL constraints on top of the defaults: a
-- constraint would reject any existing external tooling that still inserts
-- explicit NULLs, whereas a DEFAULT only kicks in when the column is omitted
-- from the INSERT — strictly safer for a live system, at the cost of not
-- being a hard guarantee. If you want the hard guarantee later, add NOT NULL
-- in a follow-up migration once you've confirmed nothing still inserts NULL
-- explicitly.
-- ============================================================================

-- ---- accommodations ---------------------------------------------------------
update accommodations set
  area = coalesce(area, ''),
  duplicate_reason = coalesce(duplicate_reason, ''),
  wifi_name = coalesce(wifi_name, ''),
  wifi_password = coalesce(wifi_password, ''),
  wifi_credentials = coalesce(wifi_credentials, ''),
  check_in_instructions = coalesce(check_in_instructions, ''),
  check_out_instructions = coalesce(check_out_instructions, ''),
  amenities = coalesce(amenities, ''),
  guidelines = coalesce(guidelines, ''),
  primary_contact = coalesce(primary_contact, ''),
  police_contact = coalesce(police_contact, ''),
  doctor_contact = coalesce(doctor_contact, ''),
  ambulance_contact = coalesce(ambulance_contact, ''),
  hospital_contact = coalesce(hospital_contact, ''),
  fire_department_contact = coalesce(fire_department_contact, ''),
  image_url = coalesce(image_url, ''),
  official_holding_company = coalesce(official_holding_company, ''),
  official_contact_name = coalesce(official_contact_name, ''),
  official_contact_number = coalesce(official_contact_number, ''),
  official_email = coalesce(official_email, ''),
  official_rep_code = coalesce(official_rep_code, ''),
  profile_reference_code = coalesce(profile_reference_code, '');

alter table accommodations
  alter column area set default '',
  alter column duplicate_reason set default '',
  alter column wifi_name set default '',
  alter column wifi_password set default '',
  alter column wifi_credentials set default '',
  alter column check_in_instructions set default '',
  alter column check_out_instructions set default '',
  alter column amenities set default '',
  alter column guidelines set default '',
  alter column primary_contact set default '',
  alter column police_contact set default '',
  alter column doctor_contact set default '',
  alter column ambulance_contact set default '',
  alter column hospital_contact set default '',
  alter column fire_department_contact set default '',
  alter column image_url set default '';
-- (profile_reference_code and official_* deliberately left without a DEFAULT:
--  profile_reference_code is always explicitly generated by Create/Import in
--  Go, so a DB-level default would never actually be used; official_* fields
--  are legitimately "unset until an admin fills them in" and a blank default
--  isn't meaningfully different from NULL there beyond the scan safety this
--  migration's UPDATE above already provides.)

-- ---- users --------------------------------------------------------------
-- Same reasoning: profile_type/entity_type/area/municipality are nullable
-- and COALESCE'd in Go (auth.go), but backfilling removes the NULL outright
-- so a manual insert can't reintroduce it either.
update users set
  profile_type = coalesce(profile_type, ''),
  entity_type = coalesce(entity_type, ''),
  area = coalesce(area, ''),
  municipality = coalesce(municipality, '');

alter table users
  alter column profile_type set default '',
  alter column entity_type set default '',
  alter column area set default '',
  alter column municipality set default '';
-- accommodation_id / entity_id stay nullable bigints with no default —
-- these are genuinely "does this user have one or not" and Go already
-- COALESCEs them to 0 on read, which is the correct "not set" sentinel for
-- an int64 field with no natural zero-collision (id 0 is never issued by
-- `generated by default as identity`, which starts at 1).
